"""Create tasks table

Revision ID: 159c77ad120c
Revises: b42f8988a4a3
Create Date: 2026-01-21 21:21:28.773416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159c77ad120c'
down_revision = 'b42f8988a4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
