"""Add planner fields to task (all nullable for sqlite)

Revision ID: 340a297ef61d
Revises: 159c77ad120c
Create Date: 2026-01-21 22:02:24.741147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340a297ef61d'
down_revision = '159c77ad120c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_planned_for'), ['planned_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_task_type'), ['task_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_task_type'))
        batch_op.drop_index(batch_op.f('ix_task_planned_for'))
        batch_op.drop_index(batch_op.f('ix_task_due_date'))
        batch_op.drop_column('due_date')
        batch_op.drop_column('task_type')

    # ### end Alembic commands ###
